services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - "./Source:/var/www/html/"

  db:
    image: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    ports:
      - "8001:3306"  # Corrected port mapping
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
